parameters:
    bridge.finder.uri: http://www.meethue.com/api/nupnp
    guzzle.client.config:
        cookies: true
        verify: false

services:
    guzzle.client:
        class: GuzzleHttp\Client
        arguments: ['%guzzle.client.config%']

    hue.bridge.finder:
        class: HueBundle\Services\BridgeFinder
        arguments: ["@guzzle.client", "%bridge.finder.uri%"]

    hue.bridge.user:
        class: HueBundle\Services\BridgeUser
        arguments: ["@hue.session", "@hue.client", "@doctrine.orm.default_entity_manager"]

    hue.session:
        class: HueBundle\Services\HueSession
        arguments: ["@session"]

    hue.client:
        class: HueBundle\Services\HueClient
        arguments: ["@hue.session"]

    hue.user.provider:
        class: HueBundle\Security\User\HueUserProvider
        arguments: ["@doctrine.orm.default_entity_manager"]

    hue.user.authenticator:
        class: HueBundle\Security\HueUserAuthenticator
        arguments: ["@router", "@hue.session", "@event_dispatcher"]

    hue.user.syncer:
        class: HueBundle\Services\Integration\UserSyncer
        arguments: ["@doctrine.orm.default_entity_manager", "@hue.client", "@logger"]

    hue.event.listener:
        class: HueBundle\EventListener\HueAuthorizeListener
        arguments: ["@hue.user.syncer"]
        tags:
            - { name: kernel.event_listener, event: client.authorized, method: onClientAuthorized }

    hue.interaction.group:
        class: HueBundle\Services\Interaction\HueGroup
        arguments: []
