services:
#    hue.example:
#        class: HueBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    hue.client:
        class: Phue\Client
        arguments: ["%hue_bridge_ip%", "%hue_username%"]
    hue.authorize:
        class: HueBundle\Services\Authorizer
        arguments: ["@hue.client"]
