parameters:
    bridge.finder.uri: http://www.meethue.com/api/nupnp
    guzzle.client.config:
        cookies: true
        verify: false

services:
    guzzle.client:
        class: GuzzleHttp\Client
        arguments: ['%guzzle.client.config%']

    hue.bridge.finder:
        class: HueBundle\Services\BridgeFinder
        arguments: ["%bridge.finder.uri%"]

    hue.client:
        class: HueBundle\Services\Client
        arguments: ["@hue.bridge.finder", "%hue_username%"]

    hue.authorizer:
        class: HueBundle\Services\Authorizer
        arguments: ["@hue.client"]
