services:
    hue.client:
        class: Phue\Client
        arguments: ["%hue_bridge_ip%", "%hue_username%"]
    hue.authorizer:
        class: HueBundle\Services\Authorizer
        arguments: ["@hue.client"]
